version: '3.8'
services:
  app:
    build: ..
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - db
  redis:
    image: redis:7
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: example
  prometheus:
    image: prom/prometheus
  grafana:
    image: grafana/grafana
