version: "3.9"
services:
  api:
    build: ../api
    ports: ["8080:8080"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    ports: ["6379:6379"]
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: omni
      POSTGRES_USER: omni
      POSTGRES_DB: omni
    ports: ["5432:5432"]
  clickhouse:
    image: clickhouse/clickhouse-server:24
    ports: ["9000:9000","8123:8123"]
  prometheus:
    image: prom/prometheus:latest
    volumes: ["./prometheus:/etc/prometheus"]
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
