groups:
- name: omni.rules
  rules:
  - alert: DataFeedStale
    expr: omni_quotes_lag_ms > 2000
    for: 2m
    labels: {severity: critical}
    annotations: {summary: "Quotes lag > 2s"}
  - alert: HighLegLatencyP95
    expr: histogram_quantile(0.95, sum(rate(omni_executor_leg_latency_ms_bucket[5m])) by (le))
          > 0.9
    for: 5m
    labels: {severity: warning}
    annotations: {summary: "Executor leg latency p95 > 900ms"}
  - alert: ErrorRateHigh
    expr: increase(omni_error_total[5m]) > 5
    for: 5m
    labels: {severity: warning}
    annotations: {summary: "High error count in last 5m"}
