global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files: ["alerts.yml"]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'omni-app'
    static_configs:
      - targets: ['api:8080']
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
