global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs: [{ targets: ["prometheus:9090"] }]

  - job_name: "pushgateway"
    honor_labels: true                # برای نگه‌داشتن job/instance ارسال‌شده
    static_configs: [{ targets: ["pushgateway:9091"] }]

  - job_name: "redis"
    static_configs: [{ targets: ["redis:6379"] }]
    metrics_path: /metrics            # اگر exporter دارید؛ در غیر این صورت حذف

  - job_name: "api"
    static_configs: [{ targets: ["api:8080"] }]
    metrics_path: /metrics            # اسکریپت API باید این را ارائه دهد
