binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  rest_endpoint: https://api.binance.com
  maker_fee_bps: 1
  taker_fee_bps: 5
okx:
  api_key: "${OKX_API_KEY}"
  api_secret: "${OKX_API_SECRET}"
  rest_endpoint: https://www.okx.com
  maker_fee_bps: 1
  taker_fee_bps: 5
internal:
  rest_endpoint: http://internal.cex
  maker_fee_bps: 0
  taker_fee_bps: 0
